//		b.ID AS id
//		b.BUSI_COMP_LOGO AS busiCompLogo
//		b.BUSI_COMP_CODE AS busiCompCode
//		b.BUSI_COMP_LEVEL AS busiCompLevel
//		b.BUSI_COMP_PRODUCT AS busiCompProduct
//		b.BUSI_COMP_TYPE AS busiCompType
//		b.BUSI_COMP_NICK AS busiCompNick
//		b.BUSI_COMP_NAME AS busiCompName
//		b.BUSI_COMP_SHORT_NAME AS busiCompShortName
//		b.BUSI_COMP_CATEGORY AS busiCompCategory
//		b.BUSI_COMP_STIME AS busiCompStime
//		b.BUSI_COMP_ETIME AS busiCompEtime
//		b.BUSI_COMP_POST AS busiCompPost
//		b.BUSI_COMP_PHONE AS busiCompPhone
//		b.BUSI_COMP_LCODE AS busiCompLcode
//		b.BUSI_COMP_FAX AS busiCompFax
//		b.BUSI_COMP_TAX AS busiCompTax
//		b.BUSI_COMP_TAXNAME AS busiCompTaxname
//		b.BUSI_COMP_TAXBANK AS busiCompTaxbank
//		b.BUSI_COMP_BANKNUM AS busiCompBanknum
//		b.BUSI_COMP_VBRK AS busiCompVbrk
//		b.BUSI_COMP_ONLINE AS busiCompOnline
//		b.BUSI_COMP_IMG1 AS busiCompImg1
//		b.BUSI_COMP_IMG2 AS busiCompImg2
//		b.BUSI_COMP_IMG3 AS busiCompImg3
//		b.BUSI_COMP_IMG4 AS busiCompImg4
//		b.BUSI_COMP_IMG5 AS busiCompImg5
//		b.BUSI_COMP_IMG6 AS busiCompImg6
//		b.BUSI_COMP_IMG7 AS busiCompImg7
//		b.BUSI_COMP_IMG8 AS busiCompImg8
//		b.BUSI_COMP_IMG9 AS busiCompImg9
//		b.GOLD AS gold
//		b.CAPITAL AS capital
//		b.CCAPITAL AS ccapital
//		b.REMARK AS remark
//		b.RATIO AS ratio
//		b.ID_NO AS idNo
//		b.ID_PHOTO AS idPhoto
//		b.BUSINESS_LICENSE AS businessLicense
//		b.REGCERTIFICATE AS regcertificate
//		b.TAXPAYER_QUALIFICATION AS taxpayerQualification
//		b.MAIN_BUSINESS_SCOPE AS mainBusinessScope
//		b.ALIPAY_ACCOUNT AS alipayAccount
//		b.OPENBANK_ACCOUNT AS openbankAccount
//		b.OPENBANK_ADDRESS AS openbankAddress
//		b.WEIXIN_NUMBER AS weixinNumber
//		b.QRCODE AS qrcode
//		b.DEL_STATE AS delState
//		b.DEPT_ID AS deptId
//		b.UID AS uid
//		b.BID AS bid
//		b.AID AS aid
//		b.UPDATE_BY AS updateBy
//		b.UPDATE_TIME AS updateTime
//		b.CREATE_TIME AS createTime
//		b.CREATE_BY AS createBy
//		b.PARAM1 AS param1
//		b.PARAM2 AS param2
//		b.PARAM3 AS param3
//		b.PARAM4 AS param4
//		b.PARAM5 AS param5
//		b.PARAM6 AS param6
//		b.PARAM7 AS param7
//		b.PARAM8 AS param8
//		b.PARAM9 AS param9
//		b.PARAM10 AS param10